
version: '2.2'
services:
  app:
    container_name: ts-node-docker
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  postgres:
    build: ./src/database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
