
version: '2.2'
services:
  app:
    restart: on-failure
    build: .
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./nodejs2022Q4-service:/src
    depends_on:
      - postgres

  postgres:
    build: ./src/database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
