
version: '3.3'
services:
  app:
    container_name: lib_app
    restart: always
    build: .
    networks:
      - mynetwork
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
      - ./logs:/usr/src/logs
    depends_on:
      - postgres

  postgres:
    container_name: lib_database
    build: ./src/database
    networks:
      - mynetwork
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  mynetwork:
    driver: bridge
